import { Injectable } from '@angular/core';
import { of, Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class TimeTableService {
  createForAcademicYear(id: number, data: any): any {
    return this.http.post(`api/academic-year/${id}/time-tables`, data)
  }

  daysOfTheWeek$: Observable<any[]> = of([
    { id: 1, name: 'Monday' },
    { id: 2, name: 'Tuesday' },
    { id: 3, name: 'Wednesday' },
    { id: 4, name: 'Thursday' },
    { id: 5, name: 'Friday' }

  ]);

  groupByDayOfWeek(values: any[]) {

    return values.reduce((prev, next) => {
      const dayOfWeek = prev[next.dayOfWeekName] || {};
      const stream = dayOfWeek[next.streamName] || {};
      return {
        ...prev,
        [next.dayOfWeekName]: {
          ...dayOfWeek,
          [next.streamName]: {
            ...stream,
            [next.timeValue]: next
          }
        }
      };
    }, {});
  }

  getForAcademicYear(id: number): Observable<any[]> {
    return this.http.get<any[]>(`api/academic-year/${id}/time-tables`);
    // return of([{
    //   timeId: 1,
    //   timeValue: '08:00:00 - 09:00:00',
    //   streamId: 1,
    //   streamName: 'R',
    //   teacherId: 1,
    //   teacherName: 'Mr Johnson Kamau',
    //   dayOfWeekId: 1,
    //   dayOfWeekName: 'Monday',
    //   subjectId: 1,
    //   subjectName: 'LA',
    //   classLevelId: 1,
    //   classLevelName: 'PP1',
    //   roomId: 1,
    //   roomAbbr: 'PP1 R'
    // }]);
    // return of([
    //   {
    //     timeId: 1,
    //     timeValue: '08:00:00 - 09:00:00',
    //     streamId: 1,
    //     streamName: 'R',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R'
    //   },
    //   {
    //     timeId: 2,
    //     timeValue: '09:00:00 - 10:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R',
    //     streamId: 1,
    //     streamName: 'R',
    //   },
    //   {
    //     timeId: 3,
    //     timeValue: '11:00:00 - 12:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R',
    //     streamId: 1,
    //     streamName: 'R',
    //   },
    //   {
    //     timeId: 1,
    //     timeValue: '08:00:00 - 09:00:00',
    //     streamId: 2,
    //     streamName: 'B',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R'
    //   },
    //   {
    //     timeId: 2,
    //     timeValue: '09:00:00 - 10:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 2,
    //     roomAbbr: 'PP1 B',
    //     streamId: 2,
    //     streamName: 'B',
    //   },
    //   {
    //     timeId: 3,
    //     timeValue: '11:00:00 - 12:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 2,
    //     roomAbbr: 'PP1 B',
    //     streamId: 2,
    //     streamName: 'B',
    //   },

    //   {
    //     timeId: 1,
    //     timeValue: '08:00:00 - 09:00:00',
    //     streamId: 1,
    //     streamName: 'R',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 2,
    //     dayOfWeekName: 'Tuesday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R'
    //   },
    //   {
    //     timeId: 2,
    //     timeValue: '09:00:00 - 10:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 2,
    //     dayOfWeekName: 'Tuesday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R',
    //     streamId: 1,
    //     streamName: 'R',
    //   },
    //   {
    //     timeId: 3,
    //     timeValue: '11:00:00 - 12:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 2,
    //     dayOfWeekName: 'Tuesday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R',
    //     streamId: 1,
    //     streamName: 'R',
    //   },
    //   {
    //     timeId: 1,
    //     timeValue: '08:00:00 - 09:00:00',
    //     streamId: 2,
    //     streamName: 'B',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 2,
    //     dayOfWeekName: 'Tuesday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R'
    //   },
    //   {
    //     timeId: 2,
    //     timeValue: '09:00:00 - 10:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 2,
    //     dayOfWeekName: 'Tuesday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 2,
    //     roomAbbr: 'PP1 B',
    //     streamId: 2,
    //     streamName: 'B',
    //   },
    //   {
    //     timeId: 3,
    //     timeValue: '11:00:00 - 12:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 2,
    //     dayOfWeekName: 'Tuesday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 1,
    //     classLevelName: 'PP1',
    //     roomId: 2,
    //     roomAbbr: 'PP1 B',
    //     streamId: 2,
    //     streamName: 'B',
    //   },

    //   {
    //     timeId: 1,
    //     timeValue: '08:00:00 - 09:00:00',
    //     streamId: 1,
    //     streamName: 'R',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 2,
    //     classLevelName: 'PP2',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R'
    //   },
    //   {
    //     timeId: 2,
    //     timeValue: '09:00:00 - 10:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 2,
    //     classLevelName: 'PP2',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R',
    //     streamId: 1,
    //     streamName: 'R',
    //   },
    //   {
    //     timeId: 3,
    //     timeValue: '11:00:00 - 12:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 2,
    //     classLevelName: 'PP2',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R',
    //     streamId: 1,
    //     streamName: 'R',
    //   },
    //   {
    //     timeId: 1,
    //     timeValue: '08:00:00 - 09:00:00',
    //     streamId: 2,
    //     streamName: 'B',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 2,
    //     classLevelName: 'PP2',
    //     roomId: 1,
    //     roomAbbr: 'PP1 R'
    //   },
    //   {
    //     timeId: 2,
    //     timeValue: '09:00:00 - 10:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 2,
    //     classLevelName: 'PP2',
    //     roomId: 2,
    //     roomAbbr: 'PP1 B',
    //     streamId: 2,
    //     streamName: 'B',
    //   },
    //   {
    //     timeId: 3,
    //     timeValue: '11:00:00 - 12:00:00',
    //     teacherId: 1,
    //     teacherName: 'Mr Johnson Kamau',
    //     dayOfWeekId: 1,
    //     dayOfWeekName: 'Monday',
    //     subjectId: 1,
    //     subjectName: 'LA',
    //     classLevelId: 2 ,
    //     classLevelName: 'PP2',
    //     roomId: 2,
    //     roomAbbr: 'PP1 B',
    //     streamId: 2,
    //     streamName: 'B',
    //   },
    // ]);
  }

  constructor(private http: HttpClient) { }
}
